apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: andherson1039/prueba-gha:ed4d258dac7ae59176ecc33cc4a8189ef7772e9c
        ports:
        - containerPort: 80
