apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: andherson1039/prueba-gha:bc7b91c6d7c16f0c440c39149964323a56b0d70b
        ports:
        - containerPort: 80
