name: CI docker build and SonarQube test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel-redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Redundancy workflow
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
          
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Primer workflow
        run: ls -las

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: andherson1039/prueba-gha:${{ github.sha }}

      - name: Update deployment.yaml
        run: |
          cat argocd/deployment.yaml
          sed -i "s|image: andherson1039/prueba-gha:[0-9a-zA-Z]*|image: andherson1039/prueba-gha:${{ github.sha }}|g" argocd/deployment.yaml
          cat argocd/deployment.yaml

      - name: Commit changes
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add argocd/deployment.yaml
          git commit -m "generated"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main


