name: CI docker build and SonarQube test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  cancel-redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Redundancy workflow
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}


  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pr: true
            main: false
          - pr: false
            main: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: SonarCloud Scan
        if: ${{ matrix.pr == true }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-html:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          context: app/
          push: false
          tags: andherson1039/prueba-gha:${{ github.sha }}

      - name: Update deployment.yaml
        run: |
          cat argocd/deployment.yaml
          sed -i "s|image: andherson1039/prueba-gha:[0-9a-zA-Z]*|image: andherson1039/prueba-gha:${{ github.sha }}|g" argocd/deployment.yaml
          cat argocd/deployment.yaml

      - name: Commit changes and push
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          branches=("main" "branch1" "branch2" "branch3") 
          git add argocd/deployment.yaml
          git commit -m "generated"
          git push



