name: andherson test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: primer workflow
        run: ls -las
