name: andherson test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Primer workflow
        run: ls -las

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: andherson1039/prueba-gha:${{ github.sha }}


